//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapLinkConnector.MaplinkV3_AddressFinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultRange", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class ResultRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int pageIndexField;
        
        private int recordsPerPageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                if ((this.pageIndexField.Equals(value) != true)) {
                    this.pageIndexField = value;
                    this.RaisePropertyChanged("pageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int recordsPerPage {
            get {
                return this.recordsPerPageField;
            }
            set {
                if ((this.recordsPerPageField.Equals(value) != true)) {
                    this.recordsPerPageField = value;
                    this.RaisePropertyChanged("recordsPerPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POIInfo", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class POIInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapLinkConnector.MaplinkV3_AddressFinder.POILocation[] poiLocationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                if ((this.recordCountField.Equals(value) != true)) {
                    this.recordCountField = value;
                    this.RaisePropertyChanged("recordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                if ((this.pageCountField.Equals(value) != true)) {
                    this.pageCountField = value;
                    this.RaisePropertyChanged("pageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MapLinkConnector.MaplinkV3_AddressFinder.POILocation[] poiLocations {
            get {
                return this.poiLocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.poiLocationsField, value) != true)) {
                    this.poiLocationsField = value;
                    this.RaisePropertyChanged("poiLocations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POILocation", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class POILocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        private bool carAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataSourceField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.City cityField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Point pointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                if ((this.carAccessField.Equals(value) != true)) {
                    this.carAccessField = value;
                    this.RaisePropertyChanged("carAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.dataSourceField, value) != true)) {
                    this.dataSourceField = value;
                    this.RaisePropertyChanged("dataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point {
            get {
                return this.pointField;
            }
            set {
                if ((object.ReferenceEquals(this.pointField, value) != true)) {
                    this.pointField = value;
                    this.RaisePropertyChanged("point");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double xField;
        
        private double yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string houseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.City cityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.houseNumberField, value) != true)) {
                    this.houseNumberField = value;
                    this.RaisePropertyChanged("houseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressOptions", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class AddressOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int matchTypeField;
        
        private bool usePhoneticField;
        
        private int searchTypeField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.ResultRange resultRangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int matchType {
            get {
                return this.matchTypeField;
            }
            set {
                if ((this.matchTypeField.Equals(value) != true)) {
                    this.matchTypeField = value;
                    this.RaisePropertyChanged("matchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool usePhonetic {
            get {
                return this.usePhoneticField;
            }
            set {
                if ((this.usePhoneticField.Equals(value) != true)) {
                    this.usePhoneticField = value;
                    this.RaisePropertyChanged("usePhonetic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int searchType {
            get {
                return this.searchTypeField;
            }
            set {
                if ((this.searchTypeField.Equals(value) != true)) {
                    this.searchTypeField = value;
                    this.RaisePropertyChanged("searchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public MapLinkConnector.MaplinkV3_AddressFinder.ResultRange resultRange {
            get {
                return this.resultRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.resultRangeField, value) != true)) {
                    this.resultRangeField = value;
                    this.RaisePropertyChanged("resultRange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class AddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation[] addressLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                if ((this.recordCountField.Equals(value) != true)) {
                    this.recordCountField = value;
                    this.RaisePropertyChanged("recordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                if ((this.pageCountField.Equals(value) != true)) {
                    this.pageCountField = value;
                    this.RaisePropertyChanged("pageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation[] addressLocation {
            get {
                return this.addressLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.addressLocationField, value) != true)) {
                    this.addressLocationField = value;
                    this.RaisePropertyChanged("addressLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressLocation", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class AddressLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keyField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Address addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipRField;
        
        private bool carAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataSourceField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Point pointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Address address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zipL {
            get {
                return this.zipLField;
            }
            set {
                if ((object.ReferenceEquals(this.zipLField, value) != true)) {
                    this.zipLField = value;
                    this.RaisePropertyChanged("zipL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zipR {
            get {
                return this.zipRField;
            }
            set {
                if ((object.ReferenceEquals(this.zipRField, value) != true)) {
                    this.zipRField = value;
                    this.RaisePropertyChanged("zipR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                if ((this.carAccessField.Equals(value) != true)) {
                    this.carAccessField = value;
                    this.RaisePropertyChanged("carAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.dataSourceField, value) != true)) {
                    this.dataSourceField = value;
                    this.RaisePropertyChanged("dataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point {
            get {
                return this.pointField;
            }
            set {
                if ((object.ReferenceEquals(this.pointField, value) != true)) {
                    this.pointField = value;
                    this.RaisePropertyChanged("point");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapOptions", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class MapOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool scaleBarField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.MapSize mapSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool scaleBar {
            get {
                return this.scaleBarField;
            }
            set {
                if ((this.scaleBarField.Equals(value) != true)) {
                    this.scaleBarField = value;
                    this.RaisePropertyChanged("scaleBar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.MapSize mapSize {
            get {
                return this.mapSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.mapSizeField, value) != true)) {
                    this.mapSizeField = value;
                    this.RaisePropertyChanged("mapSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapSize", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class MapSize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int widthField;
        
        private int heightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapInfo", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class MapInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Extent extentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Extent extent {
            get {
                return this.extentField;
            }
            set {
                if ((object.ReferenceEquals(this.extentField, value) != true)) {
                    this.extentField = value;
                    this.RaisePropertyChanged("extent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Extent", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class Extent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double XMinField;
        
        private double YMinField;
        
        private double XMaxField;
        
        private double YMaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double XMin {
            get {
                return this.XMinField;
            }
            set {
                if ((this.XMinField.Equals(value) != true)) {
                    this.XMinField = value;
                    this.RaisePropertyChanged("XMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double YMin {
            get {
                return this.YMinField;
            }
            set {
                if ((this.YMinField.Equals(value) != true)) {
                    this.YMinField = value;
                    this.RaisePropertyChanged("YMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double XMax {
            get {
                return this.XMaxField;
            }
            set {
                if ((this.XMaxField.Equals(value) != true)) {
                    this.XMaxField = value;
                    this.RaisePropertyChanged("XMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double YMax {
            get {
                return this.YMaxField;
            }
            set {
                if ((this.YMaxField.Equals(value) != true)) {
                    this.YMaxField = value;
                    this.RaisePropertyChanged("YMax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityLocationInfo", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class CityLocationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapLinkConnector.MaplinkV3_AddressFinder.CityLocation[] cityLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                if ((this.recordCountField.Equals(value) != true)) {
                    this.recordCountField = value;
                    this.RaisePropertyChanged("recordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                if ((this.pageCountField.Equals(value) != true)) {
                    this.pageCountField = value;
                    this.RaisePropertyChanged("pageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MapLinkConnector.MaplinkV3_AddressFinder.CityLocation[] cityLocation {
            get {
                return this.cityLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.cityLocationField, value) != true)) {
                    this.cityLocationField = value;
                    this.RaisePropertyChanged("cityLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityLocation", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class CityLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.City cityField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Point pointField;
        
        private bool carAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipRangeStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipRangeEndField;
        
        private bool capitalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point {
            get {
                return this.pointField;
            }
            set {
                if ((object.ReferenceEquals(this.pointField, value) != true)) {
                    this.pointField = value;
                    this.RaisePropertyChanged("point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                if ((this.carAccessField.Equals(value) != true)) {
                    this.carAccessField = value;
                    this.RaisePropertyChanged("carAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zipRangeStart {
            get {
                return this.zipRangeStartField;
            }
            set {
                if ((object.ReferenceEquals(this.zipRangeStartField, value) != true)) {
                    this.zipRangeStartField = value;
                    this.RaisePropertyChanged("zipRangeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zipRangeEnd {
            get {
                return this.zipRangeEndField;
            }
            set {
                if ((object.ReferenceEquals(this.zipRangeEndField, value) != true)) {
                    this.zipRangeEndField = value;
                    this.RaisePropertyChanged("zipRangeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool capital {
            get {
                return this.capitalField;
            }
            set {
                if ((this.capitalField.Equals(value) != true)) {
                    this.capitalField = value;
                    this.RaisePropertyChanged("capital");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrossStreetLocation", Namespace="http://webservices.maplink2.com.br")]
    [System.SerializableAttribute()]
    public partial class CrossStreetLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.City cityField;
        
        private MapLinkConnector.MaplinkV3_AddressFinder.Point pointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string crossStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point {
            get {
                return this.pointField;
            }
            set {
                if ((object.ReferenceEquals(this.pointField, value) != true)) {
                    this.pointField = value;
                    this.RaisePropertyChanged("point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string crossStreet {
            get {
                return this.crossStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.crossStreetField, value) != true)) {
                    this.crossStreetField = value;
                    this.RaisePropertyChanged("crossStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.maplink2.com.br", ConfigurationName="MaplinkV3_AddressFinder.AddressFinderSoap")]
    public interface AddressFinderSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/findPOI", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.findPOIResponse findPOI(MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequest request);
        
        // CODEGEN: Generating message contract since element name address from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/findAddress", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.findAddressResponse findAddress(MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequest request);
        
        // CODEGEN: Generating message contract since element name point from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/getAddress", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.getAddressResponse getAddress(MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequest request);
        
        // CODEGEN: Generating message contract since element name address from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/getXY", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.getXYResponse getXY(MapLinkConnector.MaplinkV3_AddressFinder.getXYRequest request);
        
        // CODEGEN: Generating message contract since element name address from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/getXYRadiusWithMap", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapResponse getXYRadiusWithMap(MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequest request);
        
        // CODEGEN: Generating message contract since element name cidade from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/findCity", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.findCityResponse findCity(MapLinkConnector.MaplinkV3_AddressFinder.findCityRequest request);
        
        // CODEGEN: Generating message contract since element name cidade from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/GetCrossStreetXY", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYResponse GetCrossStreetXY(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequest request);
        
        // CODEGEN: Generating message contract since element name point from namespace http://webservices.maplink2.com.br is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.maplink2.com.br/GetCrossStreetAddress", ReplyAction="*")]
        MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressResponse GetCrossStreetAddress(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findPOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findPOI", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequestBody Body;
        
        public findPOIRequest() {
        }
        
        public findPOIRequest(MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findPOIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MapLinkConnector.MaplinkV3_AddressFinder.ResultRange resultRange;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        public findPOIRequestBody() {
        }
        
        public findPOIRequestBody(string name, MapLinkConnector.MaplinkV3_AddressFinder.City city, MapLinkConnector.MaplinkV3_AddressFinder.ResultRange resultRange, string token) {
            this.name = name;
            this.city = city;
            this.resultRange = resultRange;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findPOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findPOIResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findPOIResponseBody Body;
        
        public findPOIResponse() {
        }
        
        public findPOIResponse(MapLinkConnector.MaplinkV3_AddressFinder.findPOIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findPOIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.POIInfo findPOIResult;
        
        public findPOIResponseBody() {
        }
        
        public findPOIResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.POIInfo findPOIResult) {
            this.findPOIResult = findPOIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findAddress", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequestBody Body;
        
        public findAddressRequest() {
        }
        
        public findAddressRequest(MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Address address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public findAddressRequestBody() {
        }
        
        public findAddressRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.Address address, MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao, string token) {
            this.address = address;
            this.ao = ao;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findAddressResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findAddressResponseBody Body;
        
        public findAddressResponse() {
        }
        
        public findAddressResponse(MapLinkConnector.MaplinkV3_AddressFinder.findAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressInfo findAddressResult;
        
        public findAddressResponseBody() {
        }
        
        public findAddressResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.AddressInfo findAddressResult) {
            this.findAddressResult = findAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAddress", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequestBody Body;
        
        public getAddressRequest() {
        }
        
        public getAddressRequest(MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double tolerance;
        
        public getAddressRequestBody() {
        }
        
        public getAddressRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.Point point, string token, double tolerance) {
            this.point = point;
            this.token = token;
            this.tolerance = tolerance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAddressResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getAddressResponseBody Body;
        
        public getAddressResponse() {
        }
        
        public getAddressResponse(MapLinkConnector.MaplinkV3_AddressFinder.getAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation getAddressResult;
        
        public getAddressResponseBody() {
        }
        
        public getAddressResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation getAddressResult) {
            this.getAddressResult = getAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getXY", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getXYRequestBody Body;
        
        public getXYRequest() {
        }
        
        public getXYRequest(MapLinkConnector.MaplinkV3_AddressFinder.getXYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getXYRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Address address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public getXYRequestBody() {
        }
        
        public getXYRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.Address address, string token) {
            this.address = address;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getXYResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getXYResponseBody Body;
        
        public getXYResponse() {
        }
        
        public getXYResponse(MapLinkConnector.MaplinkV3_AddressFinder.getXYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getXYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point getXYResult;
        
        public getXYResponseBody() {
        }
        
        public getXYResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.Point getXYResult) {
            this.getXYResult = getXYResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXYRadiusWithMapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getXYRadiusWithMap", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequestBody Body;
        
        public getXYRadiusWithMapRequest() {
        }
        
        public getXYRadiusWithMapRequest(MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getXYRadiusWithMapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Address address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.MapOptions mo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int radius;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        public getXYRadiusWithMapRequestBody() {
        }
        
        public getXYRadiusWithMapRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.Address address, MapLinkConnector.MaplinkV3_AddressFinder.MapOptions mo, int radius, string token) {
            this.address = address;
            this.mo = mo;
            this.radius = radius;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXYRadiusWithMapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getXYRadiusWithMapResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapResponseBody Body;
        
        public getXYRadiusWithMapResponse() {
        }
        
        public getXYRadiusWithMapResponse(MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class getXYRadiusWithMapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.MapInfo getXYRadiusWithMapResult;
        
        public getXYRadiusWithMapResponseBody() {
        }
        
        public getXYRadiusWithMapResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.MapInfo getXYRadiusWithMapResult) {
            this.getXYRadiusWithMapResult = getXYRadiusWithMapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findCity", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findCityRequestBody Body;
        
        public findCityRequest() {
        }
        
        public findCityRequest(MapLinkConnector.MaplinkV3_AddressFinder.findCityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findCityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City cidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public findCityRequestBody() {
        }
        
        public findCityRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.City cidade, MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao, string token) {
            this.cidade = cidade;
            this.ao = ao;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findCityResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.findCityResponseBody Body;
        
        public findCityResponse() {
        }
        
        public findCityResponse(MapLinkConnector.MaplinkV3_AddressFinder.findCityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class findCityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.CityLocationInfo findCityResult;
        
        public findCityResponseBody() {
        }
        
        public findCityResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.CityLocationInfo findCityResult) {
            this.findCityResult = findCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCrossStreetXYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCrossStreetXY", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequestBody Body;
        
        public GetCrossStreetXYRequest() {
        }
        
        public GetCrossStreetXYRequest(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class GetCrossStreetXYRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.City cidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string secondStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        public GetCrossStreetXYRequestBody() {
        }
        
        public GetCrossStreetXYRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.City cidade, string firstStreet, string secondStreet, string token) {
            this.cidade = cidade;
            this.firstStreet = firstStreet;
            this.secondStreet = secondStreet;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCrossStreetXYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCrossStreetXYResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYResponseBody Body;
        
        public GetCrossStreetXYResponse() {
        }
        
        public GetCrossStreetXYResponse(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class GetCrossStreetXYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.CrossStreetLocation[] GetCrossStreetXYResult;
        
        public GetCrossStreetXYResponseBody() {
        }
        
        public GetCrossStreetXYResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.CrossStreetLocation[] GetCrossStreetXYResult) {
            this.GetCrossStreetXYResult = GetCrossStreetXYResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCrossStreetAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCrossStreetAddress", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequestBody Body;
        
        public GetCrossStreetAddressRequest() {
        }
        
        public GetCrossStreetAddressRequest(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class GetCrossStreetAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.Point point;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public GetCrossStreetAddressRequestBody() {
        }
        
        public GetCrossStreetAddressRequestBody(MapLinkConnector.MaplinkV3_AddressFinder.Point point, string token) {
            this.point = point;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCrossStreetAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCrossStreetAddressResponse", Namespace="http://webservices.maplink2.com.br", Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressResponseBody Body;
        
        public GetCrossStreetAddressResponse() {
        }
        
        public GetCrossStreetAddressResponse(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class GetCrossStreetAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation[] GetCrossStreetAddressResult;
        
        public GetCrossStreetAddressResponseBody() {
        }
        
        public GetCrossStreetAddressResponseBody(MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation[] GetCrossStreetAddressResult) {
            this.GetCrossStreetAddressResult = GetCrossStreetAddressResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressFinderSoapChannel : MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressFinderSoapClient : System.ServiceModel.ClientBase<MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap>, MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap {
        
        public AddressFinderSoapClient() {
        }
        
        public AddressFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.findPOIResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.findPOI(MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequest request) {
            return base.Channel.findPOI(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.POIInfo findPOI(string name, MapLinkConnector.MaplinkV3_AddressFinder.City city, MapLinkConnector.MaplinkV3_AddressFinder.ResultRange resultRange, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.findPOIRequestBody();
            inValue.Body.name = name;
            inValue.Body.city = city;
            inValue.Body.resultRange = resultRange;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.findPOIResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).findPOI(inValue);
            return retVal.Body.findPOIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.findAddressResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.findAddress(MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequest request) {
            return base.Channel.findAddress(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressInfo findAddress(MapLinkConnector.MaplinkV3_AddressFinder.Address address, MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.findAddressRequestBody();
            inValue.Body.address = address;
            inValue.Body.ao = ao;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.findAddressResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).findAddress(inValue);
            return retVal.Body.findAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.getAddressResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.getAddress(MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequest request) {
            return base.Channel.getAddress(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation getAddress(MapLinkConnector.MaplinkV3_AddressFinder.Point point, string token, double tolerance) {
            MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.getAddressRequestBody();
            inValue.Body.point = point;
            inValue.Body.token = token;
            inValue.Body.tolerance = tolerance;
            MapLinkConnector.MaplinkV3_AddressFinder.getAddressResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).getAddress(inValue);
            return retVal.Body.getAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.getXYResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.getXY(MapLinkConnector.MaplinkV3_AddressFinder.getXYRequest request) {
            return base.Channel.getXY(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.Point getXY(MapLinkConnector.MaplinkV3_AddressFinder.Address address, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.getXYRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.getXYRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.getXYRequestBody();
            inValue.Body.address = address;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.getXYResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).getXY(inValue);
            return retVal.Body.getXYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.getXYRadiusWithMap(MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequest request) {
            return base.Channel.getXYRadiusWithMap(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.MapInfo getXYRadiusWithMap(MapLinkConnector.MaplinkV3_AddressFinder.Address address, MapLinkConnector.MaplinkV3_AddressFinder.MapOptions mo, int radius, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapRequestBody();
            inValue.Body.address = address;
            inValue.Body.mo = mo;
            inValue.Body.radius = radius;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.getXYRadiusWithMapResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).getXYRadiusWithMap(inValue);
            return retVal.Body.getXYRadiusWithMapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.findCityResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.findCity(MapLinkConnector.MaplinkV3_AddressFinder.findCityRequest request) {
            return base.Channel.findCity(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.CityLocationInfo findCity(MapLinkConnector.MaplinkV3_AddressFinder.City cidade, MapLinkConnector.MaplinkV3_AddressFinder.AddressOptions ao, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.findCityRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.findCityRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.findCityRequestBody();
            inValue.Body.cidade = cidade;
            inValue.Body.ao = ao;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.findCityResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).findCity(inValue);
            return retVal.Body.findCityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.GetCrossStreetXY(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequest request) {
            return base.Channel.GetCrossStreetXY(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.CrossStreetLocation[] GetCrossStreetXY(MapLinkConnector.MaplinkV3_AddressFinder.City cidade, string firstStreet, string secondStreet, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYRequestBody();
            inValue.Body.cidade = cidade;
            inValue.Body.firstStreet = firstStreet;
            inValue.Body.secondStreet = secondStreet;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetXYResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).GetCrossStreetXY(inValue);
            return retVal.Body.GetCrossStreetXYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressResponse MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap.GetCrossStreetAddress(MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequest request) {
            return base.Channel.GetCrossStreetAddress(request);
        }
        
        public MapLinkConnector.MaplinkV3_AddressFinder.AddressLocation[] GetCrossStreetAddress(MapLinkConnector.MaplinkV3_AddressFinder.Point point, string token) {
            MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequest inValue = new MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequest();
            inValue.Body = new MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressRequestBody();
            inValue.Body.point = point;
            inValue.Body.token = token;
            MapLinkConnector.MaplinkV3_AddressFinder.GetCrossStreetAddressResponse retVal = ((MapLinkConnector.MaplinkV3_AddressFinder.AddressFinderSoap)(this)).GetCrossStreetAddress(inValue);
            return retVal.Body.GetCrossStreetAddressResult;
        }
    }
}
